#!/usr/bin/env escript
%% -*- erlang-indent-level: 4; indent-tabs-mode: nil -*-

-mode(compile).

main([[]]) ->
    io:fwrite("Usage: rename_db schema.DAT_file_path [FromNode ToNode]~n"),
    halt(1);
main([SchemaDATFilePath]) ->
    main([SchemaDATFilePath, "epoch@localhost", "aeternity@localhost"]);
main([SchemaDATFilePath, FromNode, ToNode]) ->
    io:fwrite("Starting node name renaming in the db from ~p to ~p~n", [FromNode, ToNode]),
    case aeu_db:change_node(SchemaDATFilePath, list_to_atom(FromNode), list_to_atom(ToNode)) of
        ok ->
            io:fwrite("Hurray! Node name renaming in the db was successful! You're good to start your node now!~n");
        {error, _Reason} = Error ->
            io:fwrite("Script changing node in the db failed: ~p~n", [Error]),
            halt(1)
    end.
