changelog:
  exclude:
    labels:
      - release/ignore
      - area/tests
      - area/ci
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking/api
        - breaking/db
        - breaking/config
        - breaking/p2p
    - title: Next Consensus
      labels:
        - breaking/consensus
    - title: Exciting New Features 🎉
      labels:
        - kind/feature
        - kind/improvement
    - title: Bugfixes 🐞
      labels:
        - kind/bugfix
        - kind/bug
    - title: Other Changes
      labels:
        - "*"
