# Small local network of three nodes using the fastest mean16
version: '3'
services:
  node1:
    image: aetrnty/epoch
    hostname: node1
    ports: ["3013:3013", "3113:3113"]
    environment:
      EPOCH_CONFIG: /home/epoch/epoch.yaml
    command: -aecore expected_mine_rate ${EPOCH_MINE_RATE:-15000}
    volumes:
      - ${PWD}/docker/epoch_node1_mean16.yaml:/home/epoch/epoch.yaml
      - node1_db:/home/epoch/node/data/mnesia
      - node1_keys:/home/epoch/node/keys

  node2:
    image: aetrnty/epoch
    hostname: node2
    environment:
      EPOCH_CONFIG: /home/epoch/epoch.yaml
    command: -aecore expected_mine_rate ${EPOCH_MINE_RATE:-15000}
    volumes:
      - ${PWD}/docker/epoch_node2_mean16.yaml:/home/epoch/epoch.yaml
      - node2_db:/home/epoch/node/data/mnesia
      - node2_keys:/home/epoch/node/keys

  node3:
    image: aetrnty/epoch
    hostname: node3
    environment:
      EPOCH_CONFIG: /home/epoch/epoch.yaml
    command: -aecore expected_mine_rate ${EPOCH_MINE_RATE:-15000}
    volumes:
      - ${PWD}/docker/epoch_node3_mean16.yaml:/home/epoch/epoch.yaml
      - node3_db:/home/epoch/node/data/mnesia
      - node3_keys:/home/epoch/node/keys

volumes:
  node1_db:
  node1_keys:
  node2_db:
  node2_keys:
  node3_db:
  node3_keys:
