@startuml
title aesc_fsm.erl's FSM logic

[*] -> Closed

Closed -> Initialized : channel_open

Error -> Closed

Initialized -> Error              : error
Initialized -> Closed             : timeout
Initialized -> Closed             : disconnect
Initialized -> Accepted           : channel_accept

Accepted -> Error                 : error
Accepted -> Closed                : timeout
Accepted -> Closed                : disconnect
Accepted -> Half_Signed           : funding_created

Half_Signed -> Error              : error
Half_Signed -> Closed             : timeout
Half_Signed -> Closed             : disconnect
Half_Signed -> Signed             : funding_signed

Signed -> Error                   : error
Signed -> Closed                  : timeout
Signed -> Disconnected            : disconnect
Signed -> Open                    : funding_locked
Signed -> Mutual_Closing          : shutdown

Open -> Error                     : error
Open -> Disconnected              : disconnect
Open -> Open                      : update_*
Open -> Mutual_Closing            : shutdown

Disconnected -> Error             : error
Disconnected -> Open              : channel_reestablish

Mutual_Closing -> Disconnected_2  : disconnect
Mutual_Closing -> Closed          : closing_signed

Disconnected_2 -> Error           : error
Disconnected_2 -> Mutual_Closing  : channel_reestablish

@enduml
