@startuml
hide empty description
title aesc_fsm.erl's FSM logic for role responder

note as info
  This diagram omits transitions for the following events which are applicable
  to almost all states:

    - (timeout)
    - disconnect
    - [error protocol_error]

  Each of these events leads to the termination of the whole FSM.

  LEGEND:

  [if some_check]  - internal logic switch or generated error
  (timeout)        - an internal event, e.g. timeout
  disconnect       - an external event, e.g. disconnect

  TODO:

  - handle_common_event channel_closing
end note

@enduml
