# coding: utf-8

"""
    Aeternity Epoch

    This is the [Aeternity](https://www.aeternity.com/) Epoch API.

    OpenAPI spec version: 1.0.0
    Contact: apiteam@aeternity.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AccountsBalances(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'accounts_balances': 'list[AccountBalance]'
    }

    attribute_map = {
        'accounts_balances': 'accounts_balances'
    }

    def __init__(self, accounts_balances=None):
        """
        AccountsBalances - a model defined in Swagger
        """

        self._accounts_balances = None

        if accounts_balances is not None:
          self.accounts_balances = accounts_balances

    @property
    def accounts_balances(self):
        """
        Gets the accounts_balances of this AccountsBalances.

        :return: The accounts_balances of this AccountsBalances.
        :rtype: list[AccountBalance]
        """
        return self._accounts_balances

    @accounts_balances.setter
    def accounts_balances(self, accounts_balances):
        """
        Sets the accounts_balances of this AccountsBalances.

        :param accounts_balances: The accounts_balances of this AccountsBalances.
        :type: list[AccountBalance]
        """

        self._accounts_balances = accounts_balances

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AccountsBalances):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
