# coding: utf-8

"""
    Aeternity Epoch

    This is the [Aeternity](https://www.aeternity.com/) Epoch API.

    OpenAPI spec version: 1.0.0
    Contact: apiteam@aeternity.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CoinbaseTx(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pubkey': 'str',
        'nonce': 'int'
    }

    attribute_map = {
        'pubkey': 'pubkey',
        'nonce': 'nonce'
    }

    def __init__(self, pubkey=None, nonce=None):
        """
        CoinbaseTx - a model defined in Swagger
        """

        self._pubkey = None
        self._nonce = None

        if pubkey is not None:
          self.pubkey = pubkey
        if nonce is not None:
          self.nonce = nonce

    @property
    def pubkey(self):
        """
        Gets the pubkey of this CoinbaseTx.

        :return: The pubkey of this CoinbaseTx.
        :rtype: str
        """
        return self._pubkey

    @pubkey.setter
    def pubkey(self, pubkey):
        """
        Sets the pubkey of this CoinbaseTx.

        :param pubkey: The pubkey of this CoinbaseTx.
        :type: str
        """

        self._pubkey = pubkey

    @property
    def nonce(self):
        """
        Gets the nonce of this CoinbaseTx.

        :return: The nonce of this CoinbaseTx.
        :rtype: int
        """
        return self._nonce

    @nonce.setter
    def nonce(self, nonce):
        """
        Sets the nonce of this CoinbaseTx.

        :param nonce: The nonce of this CoinbaseTx.
        :type: int
        """

        self._nonce = nonce

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CoinbaseTx):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
