# coding: utf-8

"""
    Aeternity Epoch

    This is the [Aeternity](https://www.aeternity.com/) Epoch API.  # noqa: E501

    OpenAPI spec version: 0.8.0
    Contact: apiteam@aeternity.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.encoded_hash import EncodedHash  # noqa: F401,E501
from swagger_client.models.unsigned_tx import UnsignedTx  # noqa: F401,E501


class CreateContractUnsignedTx(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tx': 'EncodedHash',
        'tx_hash': 'EncodedHash',
        'contract_address': 'str'
    }

    attribute_map = {
        'tx': 'tx',
        'tx_hash': 'tx_hash',
        'contract_address': 'contract_address'
    }

    def __init__(self, tx=None, tx_hash=None, contract_address=None):  # noqa: E501
        """CreateContractUnsignedTx - a model defined in Swagger"""  # noqa: E501

        self._tx = None
        self._tx_hash = None
        self._contract_address = None
        self.discriminator = None

        self.tx = tx
        self.tx_hash = tx_hash
        self.contract_address = contract_address

    @property
    def tx(self):
        """Gets the tx of this CreateContractUnsignedTx.  # noqa: E501

        Unsigned transaction object  # noqa: E501

        :return: The tx of this CreateContractUnsignedTx.  # noqa: E501
        :rtype: EncodedHash
        """
        return self._tx

    @tx.setter
    def tx(self, tx):
        """Sets the tx of this CreateContractUnsignedTx.

        Unsigned transaction object  # noqa: E501

        :param tx: The tx of this CreateContractUnsignedTx.  # noqa: E501
        :type: EncodedHash
        """
        if tx is None:
            raise ValueError("Invalid value for `tx`, must not be `None`")  # noqa: E501

        self._tx = tx

    @property
    def tx_hash(self):
        """Gets the tx_hash of this CreateContractUnsignedTx.  # noqa: E501

        Transaction's hash  # noqa: E501

        :return: The tx_hash of this CreateContractUnsignedTx.  # noqa: E501
        :rtype: EncodedHash
        """
        return self._tx_hash

    @tx_hash.setter
    def tx_hash(self, tx_hash):
        """Sets the tx_hash of this CreateContractUnsignedTx.

        Transaction's hash  # noqa: E501

        :param tx_hash: The tx_hash of this CreateContractUnsignedTx.  # noqa: E501
        :type: EncodedHash
        """
        if tx_hash is None:
            raise ValueError("Invalid value for `tx_hash`, must not be `None`")  # noqa: E501

        self._tx_hash = tx_hash

    @property
    def contract_address(self):
        """Gets the contract_address of this CreateContractUnsignedTx.  # noqa: E501

        Address of the contract to be created  # noqa: E501

        :return: The contract_address of this CreateContractUnsignedTx.  # noqa: E501
        :rtype: str
        """
        return self._contract_address

    @contract_address.setter
    def contract_address(self, contract_address):
        """Sets the contract_address of this CreateContractUnsignedTx.

        Address of the contract to be created  # noqa: E501

        :param contract_address: The contract_address of this CreateContractUnsignedTx.  # noqa: E501
        :type: str
        """
        if contract_address is None:
            raise ValueError("Invalid value for `contract_address`, must not be `None`")  # noqa: E501

        self._contract_address = contract_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateContractUnsignedTx):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
