# coding: utf-8

"""
    Aeternity Epoch

    This is the [Aeternity](https://www.aeternity.com/) Epoch API.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: apiteam@aeternity.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.generic_tx_object import GenericTxObject  # noqa: F401,E501


class SignedTxObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tx': 'GenericTxObject',
        'signatures': 'list[str]'
    }

    attribute_map = {
        'tx': 'tx',
        'signatures': 'signatures'
    }

    def __init__(self, tx=None, signatures=None):  # noqa: E501
        """SignedTxObject - a model defined in Swagger"""  # noqa: E501

        self._tx = None
        self._signatures = None
        self.discriminator = None

        if tx is not None:
            self.tx = tx
        if signatures is not None:
            self.signatures = signatures

    @property
    def tx(self):
        """Gets the tx of this SignedTxObject.  # noqa: E501


        :return: The tx of this SignedTxObject.  # noqa: E501
        :rtype: GenericTxObject
        """
        return self._tx

    @tx.setter
    def tx(self, tx):
        """Sets the tx of this SignedTxObject.


        :param tx: The tx of this SignedTxObject.  # noqa: E501
        :type: GenericTxObject
        """

        self._tx = tx

    @property
    def signatures(self):
        """Gets the signatures of this SignedTxObject.  # noqa: E501


        :return: The signatures of this SignedTxObject.  # noqa: E501
        :rtype: list[str]
        """
        return self._signatures

    @signatures.setter
    def signatures(self, signatures):
        """Sets the signatures of this SignedTxObject.


        :param signatures: The signatures of this SignedTxObject.  # noqa: E501
        :type: list[str]
        """

        self._signatures = signatures

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SignedTxObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
