build_tarball:
  parameters:
    output:
      type: string
  steps:
    - run:
        name: Build Package Tarball
        environment:
          ERLANG_ROCKSDB_OPTS: "-DWITH_BUNDLE_LZ4=ON -DWITH_BUNDLE_SNAPPY=ON"
        command: |
          # Ensure rocksdb gets build statically
          rm -rf _build/default/lib/rocksdb/
          rm -rf _build/default/lib/mnesia_rocksdb
          # Build the package
          make prod-package
          mkdir $(dirname << parameters.output>>)
          cp _build/prod/rel/aeternity/aeternity-$(cat VERSION).tar.gz << parameters.output >>

build_deb:
  parameters:
    output:
      type: string
  steps:
    - run:
        name: Build Ubuntu package (*.deb)
        environment:
          # The *clean commands are for work-around in CircleCI
          # Debian/Ubuntu package building (clean issues; fakeroot and
          # rebar3).
          #
          # The debian/rules file has conditional *clean targets based on
          # DEB_SKIP_DH_AUTO_CLEAN.
          #
          # This prevents the presence of broken/dummy debian/rules file without
          # clean targets. For example when running debuild directly without
          # `make prod-deb-package`.
          DEB_SKIP_DH_AUTO_CLEAN: "true"
          ERLANG_ROCKSDB_BUILDOPTS: "-j2"
          ERLANG_ROCKSDB_OPTS: "-DWITH_BUNDLE_LZ4=ON -DWITH_BUNDLE_SNAPPY=ON"
        command: |
          make distclean
          make prod-deb-package
          mkdir << parameters.output>>
          mv _build/../../*aeternity-node_*.deb << parameters.output>>
