fail_notification:
  steps:
    - slack/notify:
        channel: << pipeline.parameters.slack_notification_channel >>
        event: fail
        template: basic_fail_1

deploy_notification:
  steps:
    - slack/notify:
        channel: << pipeline.parameters.slack_notification_channel >>
        event: pass
        template: success_tagged_deploy_1
