fail_notification:
  steps:
    - run:
        name: artificial fail
        command: |
          false
    - slack/notify:
        branch_pattern: slack_notifications
        event: fail
        template: basic_fail_1
    - slack/notify:
        tag_pattern: << pipeline.parameters.tag_pattern >>
        event: fail
        template: basic_fail_1

deploy_notification:
  steps:
    - slack/notify:
        tag_pattern: << pipeline.parameters.tag_pattern >>
        event: pass
        template: success_tagged_deploy_1
