fail_notification:
  steps:
    - slack/notify:
        branch_pattern: << pipeline.parameters.master_branch >>
        channel: << pipeline.parameters.slack_notification_channel >>
        event: fail
        template: basic_fail_1
    - slack/notify:
        tag_pattern: << pipeline.parameters.tag_regex >>
        channel: << pipeline.parameters.slack_notification_channel >>
        event: fail
        template: basic_fail_1

deploy_notification:
  steps:
    - slack/notify:
        tag_pattern: << pipeline.parameters.tag_regex >>
        channel: << pipeline.parameters.slack_notification_channel >>
        event: pass
        template: success_tagged_deploy_1
