fail_notification:
  steps:
    - slack/notify:
        branch_pattern: << pipeline.parameters.master_branch >>
        tag_pattern: << pipeline.parameters.tag_pattern >>
        event: fail
        template: basic_fail_1

deploy_notification:
  steps:
    - slack/notify:
        branch_pattern: ""
        tag_pattern: << pipeline.parameters.tag_pattern >>
        event: pass
        template: success_tagged_deploy_1
