when: << pipeline.parameters.run_integration_sync >>
jobs:
  - deploy:
      name: deploy-integration-sync
      package_path: https://builds.aeternity.io/aeternity-$CIRCLE_SHA1-ubuntu-x86_64.tar.gz
      version: $CIRCLE_SHA1
      env: integration_sync
      downtime: 900 #15m
      context:
        - ae-slack
        - ae-vault-node
