when: << pipeline.parameters.run_integration_sync >>
jobs:
  - reset-single-node:
      name: reset-integration-sync
      env: integration_sync
      downtime: 900 #15m
      context:
        - ae-slack
        - ae-vault-node
