---
- name: Ensure aeternity network environments
  hosts: all
  remote_user: epoch
  vars:
    public_ip: "{{ ansible_ssh_host|default(ansible_host)|default(inventory_hostname) }}"
    project_root: "{{ ansible_env.HOME }}/node"
    config:
  tasks:
     - name: "Copy node keys to {{ project_root }}/{{ config.keypair.dir }}"
       copy:
         src: "{{ item }}"
         dest: "/tmp/{{ project_root }}/{{ config.keypair.dir }}"
         mode: 0600
       with_items: "{{ key_pairs }}"
       when: key_pairs is defined
